inherit_from: configs/SimuEvent/replica_office3.yaml

data:
  datadir: ${REPLICA_EVENT_ROOT}/office3
  output: output/depth_error/office3_noise050
  exp_name: gaussian_rel_050

depth_error_exp:
  enable: true
  mode: gaussian_rel
  sigma: 0.50
  seed: 2026
