inherit_from: configs/SimuEvent/replica_office3.yaml

data:
  datadir: ${REPLICA_EVENT_ROOT}/office3
  output: output/depth_error/office3_scale110
  exp_name: scale_110

depth_error_exp:
  enable: true
  mode: scale
  scale_factor: 1.10
  seed: 2026
